global:
  scrape_interval: 3s # Seberapa sering Prometheus akan mengambil metrik dari target

scrape_configs:
  - job_name: 'mlflow_model'
    static_configs:
      - targets: ['localhost:8000'] # Target dari prometheus_exporter.py
        labels:
          application: 'boston_house_predictor'
          environment: 'local'